# Generated by Django 2.2.6 on 2019-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Institute',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
