# Generated by Django 2.2.6 on 2019-12-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20191226_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='LastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
