# Generated by Django 2.2.6 on 2019-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20191226_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.TextField(max_length=20),
        ),
    ]
